spring:
  rabbitmq:
    host: 192.168.68.129
  application:
    name: 1024-massage
server:
  port: 9009


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true #为了以后服务器上可以访问