server:
  port: 9002
spring:
  application:
    name: 1024-recruit #指定服务名
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.68.129:3306/tensquare_recruit?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123
  jpa:
    database: MySQL
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://192.168.68.129:6868/eureka/
  instance:
    prefer-ip-address: true #为了以后服务器上可以访问
